services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - $PWD/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3308:3306"
    networks:
      - analysis-net

  app:
    build: .
    image: lyuxph/analysis
    restart: always
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/analysis?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowMultiQueries=true
    depends_on:
      - db
    ports:
      - "8081:8080"
    networks:
      - analysis-net

  agent:
    build: ./src/py_scripts
    image: lyuxph/agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
    ports:
      - "5001:5000"
    networks:
      - analysis-net

  web:
    build: ./web
    image: lyuxph/web
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}:8081
    depends_on:
      - app
    ports:
      - "3000:3000"
    networks:
      - analysis-net

networks:
  analysis-net:
