name: Build on DockerHub and Deploy on AWS
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build images
        run: docker compose build
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push images
        run: docker-compose push
      - name: Deploy images
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > KeyPair.pem
          chmod 400 KeyPair.pem
          ssh -o StrictHostKeyChecking=no -i "KeyPair.pem" ec2-user@ec2-18-116-212-34.us-east-2.compute.amazonaws.com 'docker-compose pull'
          ssh -o StrictHostKeyChecking=no -i "KeyPair.pem" ec2-user@ec2-18-116-212-34.us-east-2.compute.amazonaws.com 'docker-compose up -d'